// Generated by GitHub Copilot
// Main App component

import React, { useState } from "react";
import BugForm from "./components/BugForm";
import ResultsList from "./components/ResultsList";
import Spinner from "./components/Spinner";
import ErrorMessage from "./components/ErrorMessage";
import axios from "axios";
import "./App.css";

/**
 * App component – orchestrates the duplicate bug detection workflow.
 * Manages form submission, API calls, loading state, and error handling.
 */
function App() {
  const [results, setResults] = useState([]);
  const [tfsBaseUrl, setTfsBaseUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [searched, setSearched] = useState(false);

  /**
   * Handles form submission by calling the backend API.
   * @param {{ title: string, description: string }} bugData - User-submitted bug data
   */
  const handleSubmit = async (bugData) => {
    setLoading(true);
    setError("");
    setResults([]);
    setTfsBaseUrl("");
    setSearched(false);

    try {
      // In production, use relative URL (same server); in dev, proxy to localhost:5000
      const apiBase = process.env.REACT_APP_API_URL || "";
      const response = await axios.post(
        `${apiBase}/api/check-duplicate`,
        bugData,
        { timeout: 300000 } // 5-minute timeout for AI model processing
      );
      setResults(response.data.duplicates || []);
      setTfsBaseUrl(response.data.tfsBaseUrl || "");
      setSearched(true);
    } catch (err) {
      if (err.response && err.response.data && err.response.data.error) {
        setError(err.response.data.error);
      } else if (err.code === "ECONNABORTED") {
        setError("Request timed out. Please try again.");
      } else {
        setError("Failed to check for duplicates. Is the server running?");
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="app">
      <header className="app-header">
        <h1>Duplicate Bug Detector</h1>
        <p className="app-subtitle">
          Find similar bugs using AI-powered semantic search
        </p>
      </header>

      <main id="main-content">
        <BugForm onSubmit={handleSubmit} loading={loading} />

        {loading && <Spinner />}

        {error && <ErrorMessage message={error} />}

        {searched && !loading && !error && (
          <ResultsList results={results} tfsBaseUrl={tfsBaseUrl} />
        )}
      </main>
    </div>
  );
}

export default App;
