// Generated by GitHub Copilot
// Express route for duplicate bug detection

const express = require("express");
const router = express.Router();
const { fetchBugsFromAzureDevOps } = require("../services/azureDevOpsService");
const { getEmbedding, buildVocabulary } = require("../services/embeddingService");
const { cosineSimilarity } = require("../services/similarityService");

/**
 * POST /api/check-duplicate
 * Accepts a bug title and description, returns the top 5 most similar
 * existing bugs from Azure DevOps that exceed the similarity threshold.
 *
 * @param {string} req.body.title - The bug title to check
 * @param {string} req.body.description - The bug description to check
 * @returns {{ duplicates: Array<{ id: number, title: string, description: string, similarity: number }> }}
 */
router.post("/check-duplicate", async (req, res) => {
  try {
    const { title, description } = req.body;

    // Input validation (security: prevent injection and empty submissions)
    if (!title || typeof title !== "string" || title.trim().length === 0) {
      return res.status(400).json({ error: "Bug title is required." });
    }
    if (
      !description ||
      typeof description !== "string" ||
      description.trim().length === 0
    ) {
      return res.status(400).json({ error: "Bug description is required." });
    }

    // Security: limit input length to prevent abuse
    const MAX_TITLE_LENGTH = 500;
    const MAX_DESC_LENGTH = 5000;
    if (title.length > MAX_TITLE_LENGTH) {
      return res
        .status(400)
        .json({ error: `Title must be ${MAX_TITLE_LENGTH} characters or less.` });
    }
    if (description.length > MAX_DESC_LENGTH) {
      return res.status(400).json({
        error: `Description must be ${MAX_DESC_LENGTH} characters or less.`,
      });
    }

    // Sanitize input by trimming whitespace
    const sanitizedTitle = title.trim();
    const sanitizedDescription = description.trim();

    // Step 1: Fetch existing bugs from Azure DevOps
    const existingBugs = await fetchBugsFromAzureDevOps();

    if (!existingBugs || existingBugs.length === 0) {
      return res.json({ duplicates: [], message: "No existing bugs found." });
    }

    // Step 2: Build TF-IDF vocabulary from all bug texts (used in local mode)
    const userText = `${sanitizedTitle} ${sanitizedDescription}`;
    const allTexts = existingBugs.map((b) => `${b.title} ${b.description}`);
    allTexts.push(userText); // include user text in vocabulary
    buildVocabulary(allTexts);

    // Step 3: Generate embedding for the user's input
    const userEmbedding = await getEmbedding(userText);

    // Step 4: Generate embeddings for each existing bug and compute similarity
    const mode = (process.env.EMBEDDING_MODE || "local").toLowerCase();
    // TF-IDF produces lower scores than neural embeddings, so use a lower default
    const defaultThreshold = mode === "local" ? 0.15 : 0.75;
    const threshold = parseFloat(process.env.SIMILARITY_THRESHOLD) || defaultThreshold;
    const allScored = [];

    for (const bug of existingBugs) {
      const bugText = `${bug.title} ${bug.description}`;
      const bugEmbedding = await getEmbedding(bugText);
      const similarity = cosineSimilarity(userEmbedding, bugEmbedding);

      allScored.push({
        id: bug.id,
        title: bug.title,
        description: bug.description,
        similarity: parseFloat(similarity.toFixed(4)),
      });
    }

    // Sort by similarity descending
    allScored.sort((a, b) => b.similarity - a.similarity);

    // Log top 5 scores for debugging
    console.log("Top 5 similarity scores:", allScored.slice(0, 5).map((b) => `${b.id}: ${b.similarity}`));
    console.log("Threshold:", threshold);

    // Filter by threshold and return top 5
    const topResults = allScored.filter((b) => b.similarity >= threshold).slice(0, 5);

    return res.json({ duplicates: topResults });
  } catch (error) {
    const detail = error.response?.data?.message || error.message;
    console.error("Error in /check-duplicate:", detail);
    if (error.response) {
      console.error("  Status:", error.response.status);
      console.error("  Data:", JSON.stringify(error.response.data).substring(0, 500));
    }
    return res
      .status(500)
      .json({ error: `Failed to check for duplicate bugs: ${detail}` });
  }
});

module.exports = router;
