// Generated by GitHub Copilot
// Service for fetching bugs from Azure DevOps (TFS) REST API

const axios = require("axios");

/**
 * Fetches existing bug work items from Azure DevOps using WIQL query.
 * Uses a Personal Access Token (PAT) for authentication.
 *
 * @returns {Promise<Array<{ id: number, title: string, description: string }>>}
 *   Array of bug objects with id, title, and description fields.
 * @throws {Error} If the Azure DevOps API call fails or config is missing.
 *
 * Security note: PAT is read from environment variables, never hardcoded.
 */
async function fetchBugsFromAzureDevOps() {
  const orgUrl = process.env.AZURE_DEVOPS_ORG_URL;
  const project = process.env.AZURE_DEVOPS_PROJECT;
  const pat = process.env.AZURE_DEVOPS_PAT;

  // Validate required environment variables
  if (!orgUrl || !project || !pat) {
    throw new Error(
      "Azure DevOps configuration missing. Set AZURE_DEVOPS_ORG_URL, AZURE_DEVOPS_PROJECT, and AZURE_DEVOPS_PAT in .env"
    );
  }

  // Security: build base64-encoded authorization header from PAT
  const authHeader = `Basic ${Buffer.from(`:${pat}`).toString("base64")}`;

  // Step 1: Run a WIQL query to fetch bug work item IDs (limit with $top for efficiency)
  const wiqlUrl = `${orgUrl}/${encodeURIComponent(project)}/_apis/wit/wiql?api-version=7.0&$top=200`;

  const wiqlQuery = {
    query: `SELECT [System.Id] 
            FROM WorkItems 
            WHERE [System.WorkItemType] = 'Bug' 
              AND [System.State] <> 'Closed' 
            ORDER BY [System.CreatedDate] DESC`,
  };

  const wiqlResponse = await axios.post(wiqlUrl, wiqlQuery, {
    headers: {
      Authorization: authHeader,
      "Content-Type": "application/json",
    },
    timeout: 30000, // 30-second timeout for resource efficiency
  });

  const workItemRefs = wiqlResponse.data.workItems;
  if (!workItemRefs || workItemRefs.length === 0) {
    return [];
  }

  // Limit to 200 most recent bugs for efficiency (Green Software: avoid excessive API calls)
  const ids = workItemRefs.slice(0, 200).map((item) => item.id);

  // Step 2: Batch-fetch work item details (fields: Id, Title, Description)
  // Azure DevOps API supports batching up to 200 IDs at once
  const idsParam = ids.join(",");
  const detailsUrl = `${orgUrl}/${encodeURIComponent(project)}/_apis/wit/workitems?ids=${idsParam}&fields=System.Id,System.Title,System.Description&api-version=7.0`;

  const detailsResponse = await axios.get(detailsUrl, {
    headers: {
      Authorization: authHeader,
    },
    timeout: 30000,
  });

  // Step 3: Map response to clean bug objects
  const bugs = detailsResponse.data.value.map((item) => ({
    id: item.id,
    title: item.fields["System.Title"] || "",
    description: stripHtml(item.fields["System.Description"] || ""),
  }));

  return bugs;
}

/**
 * Strips HTML tags from a string. Azure DevOps descriptions may contain HTML.
 * @param {string} html - Raw HTML string
 * @returns {string} Plain text with HTML tags removed
 */
function stripHtml(html) {
  // Security: use a simple regex to strip tags; no eval or innerHTML
  return html
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

module.exports = { fetchBugsFromAzureDevOps };
