// Generated by GitHub Copilot
// Service for generating text embeddings
// Supports three modes: 'local' (TF-IDF, no API key), 'openai', or 'azure'

const axios = require("axios");

// In-memory cache for embeddings to reduce redundant computation (Green Software)
const embeddingCache = new Map();

// Global vocabulary built from all documents for TF-IDF mode
let globalVocabulary = null;
let globalIdf = null;

/**
 * Generates a vector embedding for the given text.
 * Mode is determined by EMBEDDING_MODE env var (default: 'local').
 *
 * @param {string} text - The text to generate an embedding for
 * @returns {Promise<number[]>} A vector embedding (array of floats)
 * @throws {Error} If the embedding API call fails or config is missing
 *
 * Security note: API keys are read from environment variables, never hardcoded.
 */
async function getEmbedding(text) {
  const cacheKey = text.substring(0, 500);
  if (embeddingCache.has(cacheKey)) {
    return embeddingCache.get(cacheKey);
  }

  const mode = (process.env.EMBEDDING_MODE || "local").toLowerCase();
  let embedding;

  if (mode === "azure" && process.env.AZURE_OPENAI_API_KEY) {
    embedding = await getAzureOpenAIEmbedding(text);
  } else if (mode === "openai" && process.env.OPENAI_API_KEY) {
    embedding = await getOpenAIEmbedding(text);
  } else {
    // Default: local TF-IDF (no API key needed)
    embedding = getLocalEmbedding(text);
  }

  embeddingCache.set(cacheKey, embedding);
  return embedding;
}

// ─── LOCAL TF-IDF EMBEDDING ────────────────────────────────────────────────────

/**
 * Builds the global vocabulary and IDF weights from a corpus of documents.
 * Must be called once before using getLocalEmbedding for accurate results.
 *
 * @param {string[]} documents - Array of document texts
 */
function buildVocabulary(documents) {
  const docTokens = documents.map((doc) => tokenize(doc));
  const wordSet = new Set();
  docTokens.forEach((tokens) => tokens.forEach((t) => wordSet.add(t)));

  globalVocabulary = Array.from(wordSet).sort();
  const vocabIndex = new Map();
  globalVocabulary.forEach((word, i) => vocabIndex.set(word, i));

  // Compute IDF: log(N / df) where df = number of docs containing the term
  const N = documents.length || 1;
  const df = new Array(globalVocabulary.length).fill(0);

  docTokens.forEach((tokens) => {
    const unique = new Set(tokens);
    unique.forEach((token) => {
      const idx = vocabIndex.get(token);
      if (idx !== undefined) {
        df[idx]++;
      }
    });
  });

  globalIdf = df.map((count) => Math.log((N + 1) / (count + 1)) + 1);

  // Store vocabIndex for fast lookups
  globalVocabulary._index = vocabIndex;
}

/**
 * Generates a local TF-IDF vector for the given text.
 * If no vocabulary has been built yet, creates a simple hash-based vector.
 *
 * @param {string} text - Input text
 * @returns {number[]} TF-IDF weighted vector
 */
function getLocalEmbedding(text) {
  const tokens = tokenize(text);

  if (!globalVocabulary || globalVocabulary.length === 0) {
    // Fallback: create a hash-based fixed-size vector (1024 dims)
    return hashEmbedding(tokens, 1024);
  }

  const vocabIndex = globalVocabulary._index;
  const tf = new Array(globalVocabulary.length).fill(0);

  // Compute term frequency
  tokens.forEach((token) => {
    const idx = vocabIndex.get(token);
    if (idx !== undefined) {
      tf[idx]++;
    }
  });

  // TF-IDF = tf * idf, then L2-normalize
  const tfidf = tf.map((freq, i) => freq * (globalIdf[i] || 1));
  return l2Normalize(tfidf);
}

/**
 * Creates a fixed-size hash-based embedding when no vocabulary is available.
 * Uses a simple feature hashing trick (O(n) time and space).
 *
 * @param {string[]} tokens - Tokenized words
 * @param {number} size - Vector dimensionality
 * @returns {number[]} Normalized hash vector
 */
function hashEmbedding(tokens, size) {
  const vec = new Array(size).fill(0);
  tokens.forEach((token) => {
    const hash = simpleHash(token);
    const idx = Math.abs(hash) % size;
    vec[idx] += hash > 0 ? 1 : -1;
  });
  return l2Normalize(vec);
}

/**
 * Simple deterministic hash function for strings.
 * @param {string} str
 * @returns {number}
 */
function simpleHash(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash |= 0; // Convert to 32-bit integer
  }
  return hash;
}

/**
 * Tokenizes text into lowercase words, removing punctuation and stopwords.
 * @param {string} text - Raw text
 * @returns {string[]} Array of cleaned tokens
 */
function tokenize(text) {
  const stopwords = new Set([
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will", "would", "could",
    "should", "may", "might", "shall", "can", "to", "of", "in", "for",
    "on", "with", "at", "by", "from", "as", "into", "through", "during",
    "before", "after", "above", "below", "between", "under", "again",
    "further", "then", "once", "here", "there", "when", "where", "why",
    "how", "all", "each", "every", "both", "few", "more", "most", "other",
    "some", "such", "no", "nor", "not", "only", "own", "same", "so",
    "than", "too", "very", "just", "because", "but", "and", "or", "if",
    "while", "about", "up", "out", "off", "over", "down", "it", "its",
    "this", "that", "these", "those", "i", "me", "my", "we", "our", "you",
    "your", "he", "him", "his", "she", "her", "they", "them", "their",
    "what", "which", "who", "whom", "am",
  ]);

  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((word) => word.length > 1 && !stopwords.has(word));
}

/**
 * L2-normalizes a vector so its magnitude equals 1.
 * @param {number[]} vec
 * @returns {number[]}
 */
function l2Normalize(vec) {
  let magnitude = 0;
  for (let i = 0; i < vec.length; i++) {
    magnitude += vec[i] * vec[i];
  }
  magnitude = Math.sqrt(magnitude);
  if (magnitude === 0) return vec;
  return vec.map((v) => v / magnitude);
}

// ─── OPENAI EMBEDDING ──────────────────────────────────────────────────────────

/**
 * Calls the OpenAI Embeddings API.
 * @param {string} text - Input text
 * @returns {Promise<number[]>} Embedding vector
 */
async function getOpenAIEmbedding(text) {
  const apiKey = process.env.OPENAI_API_KEY;
  const model = process.env.OPENAI_EMBEDDING_MODEL || "text-embedding-3-small";

  const response = await axios.post(
    "https://api.openai.com/v1/embeddings",
    { input: text, model },
    {
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      timeout: 30000,
    }
  );

  return response.data.data[0].embedding;
}

// ─── AZURE OPENAI EMBEDDING ────────────────────────────────────────────────────

/**
 * Calls the Azure OpenAI Embeddings API.
 * @param {string} text - Input text
 * @returns {Promise<number[]>} Embedding vector
 */
async function getAzureOpenAIEmbedding(text) {
  const apiKey = process.env.AZURE_OPENAI_API_KEY;
  const endpoint = process.env.AZURE_OPENAI_ENDPOINT;
  const deployment =
    process.env.AZURE_OPENAI_DEPLOYMENT || "text-embedding-ada-002";
  const apiVersion = "2024-02-01";

  const url = `${endpoint}/openai/deployments/${encodeURIComponent(deployment)}/embeddings?api-version=${apiVersion}`;

  const response = await axios.post(
    url,
    { input: text },
    {
      headers: { "api-key": apiKey, "Content-Type": "application/json" },
      timeout: 30000,
    }
  );

  return response.data.data[0].embedding;
}

/**
 * Clears the embedding cache. Useful for testing or memory management.
 */
function clearEmbeddingCache() {
  embeddingCache.clear();
}

module.exports = { getEmbedding, buildVocabulary, clearEmbeddingCache };
