// Generated by GitHub Copilot
// Service for generating text embeddings using a local AI model (all-MiniLM-L6-v2)
// Supports: 'local' (default, no API key), 'openai', or 'azure'

const axios = require("axios");

// In-memory cache for embeddings to reduce redundant computation (Green Software)
const embeddingCache = new Map();

// Singleton pipeline for the local transformer model
let pipelineInstance = null;
let pipelineLoading = null;

/**
 * Lazily initializes and returns the local sentence-transformer pipeline.
 * Uses @huggingface/transformers to run all-MiniLM-L6-v2 in Node.js (no API key).
 * The model is downloaded once and cached locally.
 *
 * @returns {Promise<Function>} The feature-extraction pipeline
 */
async function getLocalPipeline() {
  if (pipelineInstance) return pipelineInstance;
  if (pipelineLoading) return pipelineLoading;

  pipelineLoading = (async () => {
    const { pipeline } = await import("@huggingface/transformers");
    console.log("Loading sentence-transformer model (first request may be slow)...");
    pipelineInstance = await pipeline("feature-extraction", "Xenova/all-MiniLM-L6-v2");
    console.log("Model loaded successfully.");
    return pipelineInstance;
  })();

  return pipelineLoading;
}

/**
 * Generates a vector embedding for the given text.
 * Mode is determined by EMBEDDING_MODE env var (default: 'local').
 *
 * @param {string} text - The text to generate an embedding for
 * @returns {Promise<number[]>} A 384-dimensional embedding vector
 * @throws {Error} If the embedding call fails or config is missing
 *
 * Security note: API keys are read from environment variables, never hardcoded.
 */
async function getEmbedding(text) {
  const cacheKey = text.substring(0, 500);
  if (embeddingCache.has(cacheKey)) {
    return embeddingCache.get(cacheKey);
  }

  const mode = (process.env.EMBEDDING_MODE || "local").toLowerCase();
  let embedding;

  if (mode === "azure" && process.env.AZURE_OPENAI_API_KEY) {
    embedding = await getAzureOpenAIEmbedding(text);
  } else if (mode === "openai" && process.env.OPENAI_API_KEY) {
    embedding = await getOpenAIEmbedding(text);
  } else {
    // Default: local transformer model (true semantic embeddings, no API key)
    embedding = await getLocalTransformerEmbedding(text);
  }

  embeddingCache.set(cacheKey, embedding);
  return embedding;
}

// ─── LOCAL TRANSFORMER EMBEDDING ───────────────────────────────────────────────

/**
 * Generates a semantic embedding using all-MiniLM-L6-v2 running locally via ONNX.
 * Produces 384-dimensional normalized vectors suitable for cosine similarity.
 *
 * @param {string} text - Input text (truncated to 256 tokens by the model)
 * @returns {Promise<number[]>} Normalized 384-dim embedding vector
 */
async function getLocalTransformerEmbedding(text) {
  const extractor = await getLocalPipeline();
  const output = await extractor(text, { pooling: "mean", normalize: true });
  // Convert Float32Array to regular array for cosine similarity
  return Array.from(output.data);
}

/**
 * No-op for backward compatibility. TF-IDF vocabulary is no longer used.
 */
function buildVocabulary() {
  // No longer needed — local transformer model handles this internally
}

// ─── OPENAI EMBEDDING ──────────────────────────────────────────────────────────

/**
 * Calls the OpenAI Embeddings API.
 * @param {string} text - Input text
 * @returns {Promise<number[]>} Embedding vector
 */
async function getOpenAIEmbedding(text) {
  const apiKey = process.env.OPENAI_API_KEY;
  const model = process.env.OPENAI_EMBEDDING_MODEL || "text-embedding-3-small";

  const response = await axios.post(
    "https://api.openai.com/v1/embeddings",
    { input: text, model },
    {
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      timeout: 30000,
    }
  );

  return response.data.data[0].embedding;
}

// ─── AZURE OPENAI EMBEDDING ────────────────────────────────────────────────────

/**
 * Calls the Azure OpenAI Embeddings API.
 * @param {string} text - Input text
 * @returns {Promise<number[]>} Embedding vector
 */
async function getAzureOpenAIEmbedding(text) {
  const apiKey = process.env.AZURE_OPENAI_API_KEY;
  const endpoint = process.env.AZURE_OPENAI_ENDPOINT;
  const deployment =
    process.env.AZURE_OPENAI_DEPLOYMENT || "text-embedding-ada-002";
  const apiVersion = "2024-02-01";

  const url = `${endpoint}/openai/deployments/${encodeURIComponent(deployment)}/embeddings?api-version=${apiVersion}`;

  const response = await axios.post(
    url,
    { input: text },
    {
      headers: { "api-key": apiKey, "Content-Type": "application/json" },
      timeout: 30000,
    }
  );

  return response.data.data[0].embedding;
}

/**
 * Clears the embedding cache. Useful for testing or memory management.
 */
function clearEmbeddingCache() {
  embeddingCache.clear();
}

module.exports = { getEmbedding, buildVocabulary, clearEmbeddingCache };
