// Generated by GitHub Copilot
// Service for computing cosine similarity between embedding vectors

/**
 * Computes the cosine similarity between two vectors.
 * Cosine similarity = (A · B) / (||A|| * ||B||)
 *
 * Optimized with a single-pass O(n) algorithm for resource efficiency.
 *
 * @param {number[]} vecA - First embedding vector
 * @param {number[]} vecB - Second embedding vector
 * @returns {number} Cosine similarity score between -1 and 1
 * @throws {Error} If vectors are empty or have different lengths
 */
function cosineSimilarity(vecA, vecB) {
  if (!vecA || !vecB || vecA.length === 0 || vecB.length === 0) {
    throw new Error("Embedding vectors must not be empty.");
  }
  if (vecA.length !== vecB.length) {
    throw new Error(
      `Vector length mismatch: ${vecA.length} vs ${vecB.length}`
    );
  }

  // Single-pass computation: dot product and magnitudes simultaneously (O(n))
  let dotProduct = 0;
  let magnitudeA = 0;
  let magnitudeB = 0;

  for (let i = 0; i < vecA.length; i++) {
    dotProduct += vecA[i] * vecB[i];
    magnitudeA += vecA[i] * vecA[i];
    magnitudeB += vecB[i] * vecB[i];
  }

  magnitudeA = Math.sqrt(magnitudeA);
  magnitudeB = Math.sqrt(magnitudeB);

  // Prevent division by zero
  if (magnitudeA === 0 || magnitudeB === 0) {
    return 0;
  }

  return dotProduct / (magnitudeA * magnitudeB);
}

module.exports = { cosineSimilarity };
