// Generated by GitHub Copilot
// BugForm component – form for entering bug title and description

import React, { useState } from "react";
import "./BugForm.css";

/**
 * BugForm renders a form with title input, description textarea, and submit button.
 * Includes client-side validation and accessibility attributes.
 *
 * @param {{ onSubmit: Function, loading: boolean }} props
 */
function BugForm({ onSubmit, loading }) {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [titleError, setTitleError] = useState("");
  const [descError, setDescError] = useState("");

  /**
   * Validates and submits the form.
   * @param {React.FormEvent} e - Form submission event
   */
  const handleSubmit = (e) => {
    e.preventDefault();

    // Client-side input validation
    let valid = true;

    if (!title.trim()) {
      setTitleError("Bug title is required.");
      valid = false;
    } else if (title.trim().length > 500) {
      setTitleError("Title must be 500 characters or less.");
      valid = false;
    } else {
      setTitleError("");
    }

    if (!description.trim()) {
      setDescError("Bug description is required.");
      valid = false;
    } else if (description.trim().length > 5000) {
      setDescError("Description must be 5000 characters or less.");
      valid = false;
    } else {
      setDescError("");
    }

    if (valid) {
      onSubmit({ title: title.trim(), description: description.trim() });
    }
  };

  return (
    <form
      className="bug-form"
      onSubmit={handleSubmit}
      noValidate
      aria-label="Bug duplicate check form"
    >
      <div className="form-group">
        <label htmlFor="bug-title" className="form-label">
          Bug Title <span aria-hidden="true">*</span>
        </label>
        <input
          id="bug-title"
          type="text"
          className={`form-input ${titleError ? "form-input--error" : ""}`}
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="e.g. Login button not responding on mobile"
          disabled={loading}
          required
          aria-required="true"
          aria-invalid={!!titleError}
          aria-describedby={titleError ? "title-error" : undefined}
          maxLength={500}
          autoComplete="off"
        />
        {titleError && (
          <p id="title-error" className="form-error" role="alert">
            {titleError}
          </p>
        )}
      </div>

      <div className="form-group">
        <label htmlFor="bug-description" className="form-label">
          Bug Description <span aria-hidden="true">*</span>
        </label>
        <textarea
          id="bug-description"
          className={`form-textarea ${descError ? "form-input--error" : ""}`}
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Describe the bug in detail: steps to reproduce, expected vs actual behavior..."
          rows={6}
          disabled={loading}
          required
          aria-required="true"
          aria-invalid={!!descError}
          aria-describedby={descError ? "desc-error" : undefined}
          maxLength={5000}
        />
        {descError && (
          <p id="desc-error" className="form-error" role="alert">
            {descError}
          </p>
        )}
      </div>

      <button
        type="submit"
        className="form-button"
        disabled={loading}
        aria-busy={loading}
      >
        {loading ? "Checking..." : "Check for Duplicates"}
      </button>
    </form>
  );
}

export default BugForm;
