// Generated by GitHub Copilot
// ErrorMessage component – displays error alerts with accessibility

import React from "react";
import "./ErrorMessage.css";

/**
 * ErrorMessage displays an error banner with the given message.
 * Uses role="alert" so screen readers immediately announce the error.
 *
 * @param {{ message: string }} props
 */
function ErrorMessage({ message }) {
  if (!message) return null;

  return (
    <div className="error-message" role="alert" aria-live="assertive">
      <span className="error-icon" aria-hidden="true">
        ⚠
      </span>
      <p className="error-text">{message}</p>
    </div>
  );
}

export default ErrorMessage;
