// Generated by GitHub Copilot
// ResultsList component – displays similar bugs found by the API

import React from "react";
import "./ResultsList.css";

/**
 * ResultsList renders a list of similar bugs with title, description, and similarity score.
 * Shows an appropriate message when no duplicates are found.
 *
 * @param {{ results: Array<{ id: number, title: string, description: string, similarity: number }> }} props
 */
function ResultsList({ results }) {
  if (!results || results.length === 0) {
    return (
      <section className="results-section" aria-label="Search results">
        <div className="no-results">
          <p>No similar bugs found. This appears to be a new bug.</p>
        </div>
      </section>
    );
  }

  /**
   * Returns a CSS class and label based on the similarity score.
   * @param {number} score - Similarity score (0-1)
   * @returns {{ className: string, label: string }}
   */
  const getSimilarityLevel = (score) => {
    if (score >= 0.9) return { className: "similarity--high", label: "Very High" };
    if (score >= 0.8) return { className: "similarity--high", label: "High" };
    if (score >= 0.75) return { className: "similarity--medium", label: "Medium" };
    return { className: "similarity--low", label: "Low" };
  };

  return (
    <section className="results-section" aria-label="Similar bugs found">
      <h2 className="results-title">
        Similar Bugs Found ({results.length})
      </h2>
      <p className="results-subtitle">
        The following existing bugs match your description:
      </p>

      <ul className="results-list" role="list">
        {results.map((bug, index) => {
          const { className, label } = getSimilarityLevel(bug.similarity);
          return (
            <li key={bug.id} className="result-card" role="listitem">
              <div className="result-header">
                <span className="result-rank" aria-label={`Rank ${index + 1}`}>
                  #{index + 1}
                </span>
                <span className="result-id">Bug ID: {bug.id}</span>
                <span
                  className={`similarity-badge ${className}`}
                  aria-label={`Similarity: ${(bug.similarity * 100).toFixed(1)}%`}
                >
                  {(bug.similarity * 100).toFixed(1)}% {label}
                </span>
              </div>

              <h3 className="result-bug-title">{bug.title}</h3>

              <p className="result-description">
                {bug.description.length > 300
                  ? `${bug.description.substring(0, 300)}...`
                  : bug.description}
              </p>

              {/* Visual similarity bar for accessibility (also visual) */}
              <div
                className="similarity-bar"
                role="progressbar"
                aria-valuenow={Math.round(bug.similarity * 100)}
                aria-valuemin={0}
                aria-valuemax={100}
                aria-label={`Similarity score: ${(bug.similarity * 100).toFixed(1)}%`}
              >
                <div
                  className={`similarity-fill ${className}`}
                  style={{ width: `${bug.similarity * 100}%` }}
                />
              </div>
            </li>
          );
        })}
      </ul>
    </section>
  );
}

export default ResultsList;
