// Generated by GitHub Copilot
// ResultsList component – displays similar bugs grouped by match tier
// Includes clickable TFS links and Excel export

import React from "react";
import * as XLSX from "xlsx";
import "./ResultsList.css";

/**
 * ResultsList renders similar bugs grouped by match tier (Exact, Very High, High, Medium, Low).
 * Bug IDs link directly to TFS. Export to Excel is supported.
 *
 * @param {{ results: Array<{ id: number, title: string, description: string, similarity: number, matchTier: string }>, tfsBaseUrl: string }} props
 */
function ResultsList({ results, tfsBaseUrl }) {
  if (!results || results.length === 0) {
    return (
      <section className="results-section" aria-label="Search results">
        <div className="no-results">
          <p>No similar bugs found. This appears to be a new bug.</p>
        </div>
      </section>
    );
  }

  // Define tier order and styling
  const tierConfig = {
    "Exact Match":     { className: "tier--exact",     icon: "\u2705", borderColor: "#2e7d32" },
    "Very High Match": { className: "tier--very-high", icon: "\uD83D\uDD34", borderColor: "#e65100" },
    "High Match":      { className: "tier--high",      icon: "\uD83D\uDFE0", borderColor: "#f57c00" },
    "Medium Match":    { className: "tier--medium",    icon: "\uD83D\uDFE1", borderColor: "#fbc02d" },
    "Low Match":       { className: "tier--low",       icon: "\uD83D\uDD35", borderColor: "#1565c0" },
  };

  const tierOrder = ["Exact Match", "Very High Match", "High Match", "Medium Match", "Low Match"];

  /**
   * Returns CSS class name for the similarity badge.
   * @param {number} score - Similarity score (0-1)
   * @returns {{ className: string, label: string }}
   */
  const getSimilarityLevel = (score) => {
    if (score >= 0.90) return { className: "similarity--exact", label: "Exact" };
    if (score >= 0.70) return { className: "similarity--very-high", label: "Very High" };
    if (score >= 0.50) return { className: "similarity--high", label: "High" };
    if (score >= 0.35) return { className: "similarity--medium", label: "Medium" };
    return { className: "similarity--low", label: "Low" };
  };

  /**
   * Builds the TFS work item URL for a given bug ID.
   * @param {number} bugId - Work item ID
   * @returns {string} Full TFS URL
   */
  const getTfsUrl = (bugId) => {
    if (tfsBaseUrl) return `${tfsBaseUrl}/${bugId}`;
    return "#";
  };

  /**
   * Exports the results to an Excel (.xlsx) file.
   * Includes Bug ID, Title, Similarity %, Match Tier, Description, and TFS Link.
   */
  const handleExportExcel = () => {
    const rows = results.map((bug, index) => ({
      "Rank": index + 1,
      "Bug ID": bug.id,
      "Title": bug.title,
      "Similarity (%)": `${(bug.similarity * 100).toFixed(1)}%`,
      "Match Tier": bug.matchTier || "Low Match",
      "Description": bug.description.substring(0, 500),
      "TFS Link": getTfsUrl(bug.id),
    }));

    const worksheet = XLSX.utils.json_to_sheet(rows);

    // Auto-size columns for readability
    const colWidths = Object.keys(rows[0] || {}).map((key) => ({
      wch: Math.max(key.length, ...rows.map((r) => String(r[key]).length).slice(0, 20)) + 2,
    }));
    worksheet["!cols"] = colWidths;

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Duplicate Bug Report");
    XLSX.writeFile(workbook, `DuplicateBugReport_${new Date().toISOString().slice(0, 10)}.xlsx`);
  };

  // Group results by tier
  const grouped = {};
  for (const bug of results) {
    const tier = bug.matchTier || "Low Match";
    if (!grouped[tier]) grouped[tier] = [];
    grouped[tier].push(bug);
  }

  let globalRank = 0;

  return (
    <section className="results-section" aria-label="Similar bugs found">
      <div className="results-header-row">
        <div>
          <h2 className="results-title">
            Similar Bugs Found ({results.length})
          </h2>
          <p className="results-subtitle">
            Results sorted by similarity — click Bug ID to open in TFS.
          </p>
        </div>
        <button
          className="export-btn"
          onClick={handleExportExcel}
          aria-label="Export results to Excel"
          type="button"
        >
          <span aria-hidden="true">&#128190;</span> Export to Excel
        </button>
      </div>

      {tierOrder.map((tier) => {
        const bugs = grouped[tier];
        if (!bugs || bugs.length === 0) return null;

        const config = tierConfig[tier] || tierConfig["Low Match"];

        return (
          <div key={tier} className={`tier-group ${config.className}`}>
            <div className="tier-header" style={{ borderLeftColor: config.borderColor }}>
              <span className="tier-icon" aria-hidden="true">{config.icon}</span>
              <h3 className="tier-label">{tier}</h3>
              <span className="tier-count">({bugs.length})</span>
            </div>

            <ul className="results-list" role="list">
              {bugs.map((bug) => {
                globalRank++;
                const { className, label } = getSimilarityLevel(bug.similarity);
                return (
                  <li key={bug.id} className="result-card" role="listitem"
                      style={{ borderLeftColor: config.borderColor }}>
                    <div className="result-header">
                      <span className="result-rank" aria-label={`Rank ${globalRank}`}>
                        #{globalRank}
                      </span>
                      <a
                        href={getTfsUrl(bug.id)}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="result-id result-id--link"
                        aria-label={`Open bug ${bug.id} in TFS`}
                      >
                        Bug ID: {bug.id} &#x2197;
                      </a>
                      <span
                        className={`similarity-badge ${className}`}
                        aria-label={`Similarity: ${(bug.similarity * 100).toFixed(1)}%`}
                      >
                        {(bug.similarity * 100).toFixed(1)}% {label}
                      </span>
                    </div>

                    <h4 className="result-bug-title">{bug.title}</h4>

                    <p className="result-description">
                      {bug.description.length > 300
                        ? `${bug.description.substring(0, 300)}...`
                        : bug.description}
                    </p>

                    {/* Visual similarity bar */}
                    <div
                      className="similarity-bar"
                      role="progressbar"
                      aria-valuenow={Math.round(bug.similarity * 100)}
                      aria-valuemin={0}
                      aria-valuemax={100}
                      aria-label={`Similarity score: ${(bug.similarity * 100).toFixed(1)}%`}
                    >
                      <div
                        className={`similarity-fill ${className}`}
                        style={{ width: `${bug.similarity * 100}%` }}
                      />
                    </div>
                  </li>
                );
              })}
            </ul>
          </div>
        );
      })}
    </section>
  );
}

export default ResultsList;
