// Generated by GitHub Copilot
// Spinner component – loading indicator with accessibility

import React from "react";
import "./Spinner.css";

/**
 * Spinner renders an animated loading indicator.
 * Includes an aria-live region so screen readers announce the loading state.
 */
function Spinner() {
  return (
    <div className="spinner-container" role="status" aria-live="polite">
      <div className="spinner" aria-hidden="true">
        <div className="spinner-ring" />
      </div>
      <p className="spinner-text">Analyzing bugs for duplicates...</p>
    </div>
  );
}

export default Spinner;
